### ISSUE TITLE
 Not able to see admin panel in Granular-QA

### ISSUE THREAD

**Issue by M-madan100** [granularai/geoengine-issues#10]
**Describe the bug**
As I am admin at granular-QA but admin panel is not appearing on it

**To Reproduce**
1. Go to 'production website'
2. Click on 'Granular at the top right corner'
3. Scroll down to 'Granular-QA'
4. And there you can see the admin panel is not occuring

**Expected behavior**
Admin panel should appear and all the possible features should work that is used for admin

**Screenshots**
![Screenshot (307)](https://user-images.githubusercontent.com/76648533/195570092-6d6bbba5-d6d4-47d1-90ea-7aae45ea11ef.png)

**Additional context**

**Comment by hal-shin** [comment]
Fixed by https://github.com/granularai/GeoEngine/pull/325. Should be pushed to production soon.
