### ISSUE TITLE
Page loading takes time

### ISSUE THREAD

**Issue by M-madan100** [granularai/geoengine-issues#12]
**Describe the bug**
While we go for dashboard as an annotator it takes time to load

**To Reproduce**
1. Go to 'GeoEngine.Granular'
2. Click on 'Dashboard'
3. See error

**Expected behavior**
Should load fast

**Screenshots**
![Screenshot (319)](https://user-images.githubusercontent.com/76648533/196860754-46eb685a-6100-4eb6-a212-eb9f8c7d1210.png)

**Additional context**

**Comment by hal-shin** [comment]
We've improved the loading time of the task page.

Thanks for the issue.
