### ISSUE TITLE
Unable to access dashboard as team annotator [500 error]

### ISSUE THREAD

**Issue by suresh1200** [granularai/geoengine-issues#18]
**Describe the bug**
When navigating from explore to dashboard, I see the issue catchall screen (Unfortunately…)
Console and Network indicate a 500 error

**Screenshots**

https://user-images.githubusercontent.com/117749405/200602602-7f8967c3-fd11-42da-81e2-50ca67b2fb21.mp4

**Additional context**

**Comment by hal-shin** [comment]
Closed by https://github.com/granularai/GeoEngine/pull/467
