### ISSUE TITLE
Unable to invite annotation team members to Eagle view project - Hail Damage

### ISSUE THREAD

**Issue by Ujwal-D** [granularai/geoengine-issues#19]
**Describe the bug**
At this point, we are unable to add new members to the Eagle View - Hail Damage annotation project either as Contributor or Annotator.

**To Reproduce**
1. Go to Organization in engine.granular.ai
2. Under Invite member -> add a member - either as "annotator" or "contributor"
3. Then Click on Invite button
4. See error - "Unable to send invitations"

**Expected behavior**
Invited member(s) should receive an invitation in the form of email.

**Screenshots**
(Attached )
![E1](https://user-images.githubusercontent.com/31354853/203054016-5070aa08-9149-4fdd-bf50-6455400f6a21.png)

**Comment by sagarverma** [comment]
In the screenshot I see that email is already in pending invitations. In the org page I see that that email ID has already been added. Also annotators should be added as annotators not contributors.
