### ISSUE TITLE
Image loading time in granular geoengine is high

### ISSUE THREAD

**Issue by M-madan100** [granularai/geoengine-issues#20]
**Describe the bug**
Image loading in granular is high

**To Reproduce**
1. Go to 'dashboard'
2. Click on 'UAV Synthetic Image Quality'
3. Click on 'Begin annotation'

**Expected behavior**
Should be smooth and image loading time should be less
**Screenshots**
(https://www.loom.com/share/abd8697561504ea3b410d21a727881ae)

**Additional context**

**Comment by Ujwal-D** [comment]
Since dataset is completed - closing the issue
