### ISSUE TITLE
Stats page is not working 

### ISSUE THREAD

**Issue by tankajoshi122** [granularai/geoengine-issues#3]
**Describe the bug**
Stats page is not  working for Test organization. There are few annotations completed on the September month those data are not displaying in the chart.

**To Reproduce**
1. Go to 'My Stats' for Test Organization (cofosi3046@esmoud.com)
2. Click on 'Drop down to select Current Year'
3. It shows 'No Data'

All the Chart section inside the stat page should display some data.

![s](https://user-images.githubusercontent.
![t](https://user-images.githubusercontent.com/52836788/194242309-d0dd212c-b7d6-4974-8dd4-fddf5934a1aa.png)
com/52836788/194242255-0a2ed946-8234-4367-915b-3dfa10a690b0.png)

**Comment by hal-shin** [comment]
@tankajoshi122 Were the annotations created on the same day? If so, the stats take a day to calculate.

**Comment by tankajoshi122** [comment]
@hal-shin annotation were created on the first week of September

**Comment by tankajoshi122** [comment]
> @tankajoshi122 Were the annotations created on the same day? If so, the stats take a day to calculate.

 annotation were created on the first week of September

**Comment by hal-shin** [comment]
This item has been resolved. User stats calculation module was down for a bit.
