### ISSUE TITLE
Annotation process is not working for Test's personal Organization

### ISSUE THREAD

**Issue by tankajoshi122** [granularai/geoengine-issues#4]
**Describe the bug**
For Test organization Annotation is not working, While Annotating it throw **Could not save annotation to database** error

**To Reproduce**
1. Go to 'QA Test Task -1'
2. Click on ' Begin Annotation'
3. Start Annotating 
4. See error " _Could not save annotation to database_ "

**Expected behavior**
Annotation should save to the database without error.

**Screenshots**
![ann](https://user-images.githubusercontent.com/52836788/194548476-8a4ceef5-d50e-4a61-b50a-5ba8ff7db5d4.png)

**Comment by tankajoshi122** [comment]
https://www.loom.com/share/3861dffb8221406aba589169e027e0d1

**Comment by sid-at-granular** [comment]
It strikes me this should be a pretty high-priority issue. @hal-shin what do you think?

**Comment by hal-shin** [comment]
This item has been resolved.
