### ISSUE TITLE
Responsive 

### ISSUE THREAD

**Issue by tankajoshi122** [granularai/geoengine-issues#5]
**Describe the bug**
Responsive issue. Web page start toggling after putting cursor over the login/logout icon

**To Reproduce**
1. Go to 'Europa Homepage'
2. Click on ' hover mouse over the Login/Logout Icon'
3. See error

**Expected behavior**
Web page should be constant over mouse hover  

**Screenshots**
https://www.loom.com/share/78ad25ec2763436c962089ada4d256a5

**Additional context**

**Comment by hal-shin** [comment]
This issue has been resolved.
