### ISSUE TITLE
Tag

### ISSUE THREAD

**Issue by tankajoshi122** [granularai/geoengine-issues#8]
**Describe the bug**
While creating task it accept two letter tag but from setting while editing the task info that time it doesn't accept two letter tag.

**To Reproduce**
1. Go to 'Dashboard'
2. Click on 'any task'
3. Go to setting and update task tag 
4. See error " This tag is too short, it must be at least 3 characters."

**Expected behavior**
Tag Condition should be same for the both while creating and updating

**Screenshots**
![tag](https://user-images.githubusercontent.com/52836788/195505109-fe461769-209c-4873-8152-59393a53f6a4.png)
https://www.loom.com/share/2fb48c30ad284195a2395b025e166ef7

**Additional context**

**Comment by sagarverma** [comment]
@tankajoshi122 please be more descriptive in the issue naming. At least 5 words.

**Comment by hal-shin** [comment]
The minimum string length for tags has been updated to 2. This issue should be fixed now.
